# fly.toml app configuration file generated for duun-web on 2025-02-07T18:48:36+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'duun-web'
primary_region = 'jnb'

[build]
  dockerfile = "Web/Dockerfile"
  ignorefile = "Web/.dockerignore"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
